name: Actions Workflow 1
#on : [pull_request]
on: 
  schedule:
    - cron: "0/5 * * * *"
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd 
          ls -a
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd 
          ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main 
        with: 
          who-to-greet: Olga Olga
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
