name: NewWorkflow
on : [push]
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - name: get repository code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
